### ISSUE TITLE
find out why curseforge packager doesn't work

### ISSUE THREAD

**Issue by partouf** [partouf/AchieveAche#2]

**Comment by partouf** [comment]
Submitted a question to the new curseforge forums; https://www.curseforge.com/forums/world-of-warcraft/general/95577-packaging-after-switching-to-external-repository

**Comment by martinvd** [comment]
Someone from Curse replied.
I noticed this page btw, but not sure it can be helpful https://www.curseforge.com/docs/packaging.

**Comment by partouf** [comment]
ohhh I browsed through the old website's documentation, but did not find this one. Shall give it a go

**Comment by partouf** [comment]
Tried to find an equivalent for the WoW addons, there isn't much except for these https://wow.curseforge.com/wiki/projects/uploading-through-a-script/

Hopefully they will migrate to the new API some day.

**Comment by martinvd** [comment]
Hmm, yea I hope they will..

**Comment by partouf** [comment]
Closing issue, been able to manually upload the new versions a couple of days ago.

**Comment by martinvd** [comment]
Ah great :+1:
